import type {
  DietPreference,
  EmploymentType,
  FamilyType,
  FamilyValues,
  ForeignStatus,
  InterestRequest,
  MangalStatus,
  MaritalStatus,
  Match,
  Message,
  Notification,
  PrivacySettings,
  User,
  UserPreferences,
} from '@/types';

const now = Date.now();

const defaultPreferences: UserPreferences = {
  ageRange: [24, 33],
  distance: 80,
  genderPreference: 'female',
  lookingFor: 'marriage',
  verifiedOnly: true,
  preferredMotherTongues: [],
  preferredCommunities: [],
  preferredEducation: [],
  familyValues: ['balanced'],
};

const defaultPrivacy: PrivacySettings = {
  profileVisibility: 'all',
  photoVisibility: 'accepted-interest',
  contactPermission: 'accepted-interest',
  showOnlineStatus: true,
  showLastActive: true,
  allowVisitorAlerts: true,
  hideFromFreeMembers: false,
};

export const motherTongueOptions = ['Hindi', 'English', 'Tamil', 'Telugu', 'Kannada', 'Malayalam', 'Gujarati', 'Punjabi', 'Bengali', 'Marathi', 'Rajasthani', 'Odia', 'Sindhi'];
export const communityOptions = [
  // Patel sub-castes (Gujarati)
  'Kadva Patel', 'Leuva Patel', 'Anjana Patel', 'Matiya Patel',
  // Other Gujarati
  'Gujarati Brahmin', 'Gujarati Bania', 'Gujarati Jain',
  // Major communities
  'Punjabi', 'Punjabi Khatri', 'Punjabi Arora',
  'Malayali', 'Tamil Brahmin', 'Tamil Mudaliar', 'Tamil Chettiar',
  'Telugu Brahmin', 'Telugu Kamma', 'Telugu Reddy',
  'Kannada Brahmin', 'Kannada Vokkaliga', 'Kannada Lingayat',
  'Bengali Brahmin', 'Bengali Kayastha',
  'Marathi Brahmin', 'Marathi CKP', 'Marathi Maratha',
  'Rajput', 'Brahmin', 'Agarwal', 'Maheshwari', 'Sindhi',
  'North Indian', 'Intercaste', 'Global',
];
export const educationOptions = ['Bachelors', 'BTech', 'BPharm', 'BArch', 'MBBS', 'BDS', 'Masters', 'MTech', 'MPharm', 'MBA', 'CA', 'LLB', 'PhD'];
export const familyValueOptions: FamilyValues[] = ['traditional', 'balanced', 'progressive'];
export const familyTypeOptions: FamilyType[] = ['joint', 'nuclear'];
export const mangalStatusOptions: MangalStatus[] = ['mangal', 'non-mangal', 'not-specified'];
export const dietOptions: DietPreference[] = ['vegetarian', 'swaminarayan', 'jain', 'eggetarian', 'non-vegetarian', 'vegan'];
export const employmentTypeOptions: EmploymentType[] = ['business', 'government', 'private-mnc', 'private-company', 'self-employed'];
export const foreignStatusOptions: ForeignStatus[] = ['india-based', 'nri-usa', 'nri-uk', 'nri-canada', 'nri-australia', 'nri-gulf', 'nri-other'];
export const maritalStatusOptions: MaritalStatus[] = ['never-married', 'divorced', 'widowed', 'awaiting-divorce'];
export const incomeBracketOptions = ['Prefer not to say', 'Under 5 LPA', '5–10 LPA', '10–15 LPA', '15–25 LPA', '25–50 LPA', '50 LPA – 1 Crore', '1 Crore+'];

export function createDefaultUser(email: string, overrides: Partial<User> = {}): User {
  return {
    id: overrides.id ?? crypto.randomUUID(),
    email,
    name: overrides.name ?? email.split('@')[0],
    age: overrides.age ?? 27,
    gender: overrides.gender ?? 'other',
    location: overrides.location ?? 'Bengaluru, Karnataka',
    profession: overrides.profession ?? 'Product designer',
    bio: overrides.bio ?? '',
    photos: overrides.photos ?? [],
    interests: overrides.interests ?? ['Travel', 'Family time', 'Music'],
    preferences: {
      ...defaultPreferences,
      ...(overrides.preferences ?? {}),
    },
    matches: overrides.matches ?? [],
    likes: overrides.likes ?? [],
    shortlisted: overrides.shortlisted ?? [],
    recentlyViewed: overrides.recentlyViewed ?? [],
    recentVisitors: overrides.recentVisitors ?? [],
    blockedUsers: overrides.blockedUsers ?? [],
    notifications: {
      email: true,
      push: true,
      matches: true,
      messages: true,
      ...(overrides.notifications ?? {}),
    },
    chatDefaults: {
      readReceipts: true,
      typingIndicators: true,
      mediaAutoDownload: true,
      ...(overrides.chatDefaults ?? {}),
    },
    appearance: {
      theme: 'light',
      language: 'en',
      ...(overrides.appearance ?? {}),
    },
    verification: {
      phoneVerified: true,
      idVerified: false,
      profileReviewed: false,
      badge: 'phone',
      ...(overrides.verification ?? {}),
    },
    accountStatus: {
      emailVerified: true,
      emailVerificationRequired: false,
      emailVerificationSentAt: null,
      emailVerifiedAt: new Date(now),
      ...(overrides.accountStatus ?? {}),
    },
    privacy: {
      ...defaultPrivacy,
      ...(overrides.privacy ?? {}),
    },
    details: {
      education: 'Bachelors',
      company: 'Independent',
      annualIncome: 'Prefer not to say',
      motherTongue: 'Hindi',
      community: 'Global',
      familyValues: 'balanced',
      familyBackground: 'Warm, educated family that values kindness, stability, and mutual respect.',
      maritalStatus: 'never-married',
      height: '5\'8"',
      diet: 'vegetarian',
      nativeVillage: '',
      familyType: 'nuclear',
      mangalStatus: 'not-specified',
      employmentType: 'private-company',
      foreignStatus: 'india-based',
      smokingHabits: 'never',
      drinkingHabits: 'never',
      careerIntent: 'yes',
      ...(overrides.details ?? {}),
    },
    profileFor: overrides.profileFor ?? 'self',
    stats: {
      profileViews: 32,
      responseRate: 61,
      profileCompletion: 74,
      boostScore: 58,
      ...(overrides.stats ?? {}),
    },
    lastActiveAt: overrides.lastActiveAt ?? new Date(now - 45 * 60 * 1000),
    createdAt: overrides.createdAt ?? new Date(now - 60 * 24 * 60 * 60 * 1000),
  };
}

export const demoCurrentUser = createDefaultUser('demo@soulmate.app', {
  id: '1',
  name: 'Arjun Mehta',
  age: 29,
  gender: 'male',
  location: 'Bengaluru, Karnataka',
  profession: 'Senior Product Engineer',
  bio: 'I am building a grounded life around meaningful work, close family ties, weekend cooking, and long conversations. My parents are based in Jaipur, I work in Bengaluru, and I am looking for a warm, marriage-minded partner who values steadiness, ambition, and mutual respect.',
  photos: ['/gallery_1.jpg', '/gallery_4.jpg'],
  interests: ['Travel', 'Cooking', 'Badminton', 'Family time', 'Photography'],
  matches: ['2', '4'],
  likes: ['4', '5', '6'],
  shortlisted: ['4', '6', '7'],
  recentlyViewed: ['2', '6', '3'],
  recentVisitors: ['6', '8', '2'],
  verification: {
    phoneVerified: true,
    idVerified: true,
    profileReviewed: true,
    badge: 'id',
  },
  privacy: {
    ...defaultPrivacy,
    profileVisibility: 'matching-only',
    hideFromFreeMembers: true,
  },
  details: {
    education: 'BTech',
    company: 'Razorpay',
    annualIncome: '25–50 LPA',
    motherTongue: 'Hindi',
    community: 'North Indian',
    familyValues: 'balanced',
    familyBackground: 'Close-knit family based between Jaipur and Bengaluru, values warmth, education, and long-term commitment.',
    maritalStatus: 'never-married',
    height: '5\'11"',
    diet: 'vegetarian',
    nativeVillage: 'Sikar, Rajasthan',
    familyType: 'nuclear',
    mangalStatus: 'non-mangal',
    employmentType: 'private-mnc',
    foreignStatus: 'india-based',
    smokingHabits: 'never',
    drinkingHabits: 'occasionally',
    careerIntent: 'yes',
  },
  preferences: {
    ageRange: [25, 31],
    distance: 100,
    genderPreference: 'female',
    lookingFor: 'marriage',
    verifiedOnly: true,
    preferredMotherTongues: ['Hindi', 'English', 'Gujarati'],
    preferredCommunities: ['North Indian', 'Gujarati', 'Punjabi', 'Global'],
    preferredEducation: ['BTech', 'Masters', 'MBA'],
    familyValues: ['balanced', 'progressive'],
  },
  stats: {
    profileViews: 128,
    responseRate: 82,
    profileCompletion: 91,
    boostScore: 88,
  },
  lastActiveAt: new Date(now - 12 * 60 * 1000),
  createdAt: new Date(now - 160 * 24 * 60 * 60 * 1000),
});

export const demoProfiles: User[] = [
  createDefaultUser('nisha@example.com', {
    id: '2',
    name: 'Nisha Shah',
    age: 27,
    gender: 'female',
    location: 'Mumbai, Maharashtra',
    profession: 'Brand Strategist',
    bio: 'I split my free time between design books, Sunday lunch with family, and planning short coastal getaways. I am looking for a serious, calm partnership with someone who is kind, consistent, and excited to build a happy home.',
    photos: ['/gallery_2.jpg', '/gallery_5.jpg'],
    interests: ['Art', 'Coffee', 'Travel', 'Design', 'Yoga'],
    verification: {
      phoneVerified: true,
      idVerified: true,
      profileReviewed: true,
      badge: 'id',
    },
    details: {
      education: 'MBA',
      company: 'Nykaa',
      annualIncome: '15–25 LPA',
      motherTongue: 'Gujarati',
      community: 'Leuva Patel',
      familyValues: 'balanced',
      familyBackground: 'Business family in Mumbai with a modern outlook, close family bonds, and strong respect for education.',
      maritalStatus: 'never-married',
      height: '5\'5"',
      diet: 'swaminarayan',
      nativeVillage: 'Anand, Gujarat',
      familyType: 'joint',
      mangalStatus: 'non-mangal',
      employmentType: 'private-mnc',
      foreignStatus: 'india-based',
      smokingHabits: 'never',
      drinkingHabits: 'never',
      careerIntent: 'yes',
    },
    preferences: {
      ageRange: [27, 34],
      distance: 80,
      genderPreference: 'male',
      lookingFor: 'marriage',
      verifiedOnly: true,
      preferredMotherTongues: ['Gujarati', 'Hindi', 'English'],
      preferredCommunities: ['Gujarati', 'Intercaste', 'Global'],
      preferredEducation: ['Bachelors', 'BTech', 'Masters', 'MBA'],
      familyValues: ['balanced'],
    },
    stats: {
      profileViews: 214,
      responseRate: 86,
      profileCompletion: 95,
      boostScore: 90,
    },
    lastActiveAt: new Date(now - 18 * 60 * 1000),
    createdAt: new Date(now - 94 * 24 * 60 * 60 * 1000),
  }),
  createDefaultUser('ananya@example.com', {
    id: '3',
    name: 'Ananya Iyer',
    age: 29,
    gender: 'female',
    location: 'Chennai, Tamil Nadu',
    profession: 'Architect',
    bio: 'I enjoy heritage walks, Carnatic concerts, and quiet evenings with a good book. I connect best with thoughtful people who value culture, family warmth, and a partnership that feels steady as well as exciting.',
    photos: ['/profile_emma.jpg', '/gallery_7.jpg'],
    interests: ['Architecture', 'Heritage', 'Coffee', 'Reading', 'Travel'],
    verification: {
      phoneVerified: true,
      idVerified: false,
      profileReviewed: true,
      badge: 'phone',
    },
    details: {
      education: 'Masters',
      company: 'Design Habitat',
      annualIncome: '15–25 LPA',
      motherTongue: 'Tamil',
      community: 'Tamil Brahmin',
      familyValues: 'progressive',
      familyBackground: 'Academic family that values empathy, intellectual curiosity, and strong cultural roots.',
      maritalStatus: 'never-married',
      height: '5\'7"',
      diet: 'vegetarian',
      nativeVillage: 'Thanjavur, Tamil Nadu',
      familyType: 'nuclear',
      mangalStatus: 'mangal',
      employmentType: 'self-employed',
      foreignStatus: 'india-based',
      smokingHabits: 'never',
      drinkingHabits: 'never',
      careerIntent: 'yes',
    },
    preferences: {
      ageRange: [28, 35],
      distance: 60,
      genderPreference: 'male',
      lookingFor: 'marriage',
      verifiedOnly: false,
      preferredMotherTongues: ['Tamil', 'English'],
      preferredCommunities: ['Tamil', 'Intercaste', 'Global'],
      preferredEducation: ['Masters', 'MBA', 'PhD'],
      familyValues: ['balanced', 'progressive'],
    },
    stats: {
      profileViews: 144,
      responseRate: 63,
      profileCompletion: 87,
      boostScore: 67,
    },
    lastActiveAt: new Date(now - 9 * 60 * 60 * 1000),
    createdAt: new Date(now - 48 * 24 * 60 * 60 * 1000),
  }),
  createDefaultUser('priya@example.com', {
    id: '4',
    name: 'Priya Nair',
    age: 28,
    gender: 'female',
    location: 'Kochi, Kerala',
    profession: 'Pediatrician',
    bio: 'I want a deeply kind partnership with room for ambition, family, and a lot of laughter. I am happiest hosting cousins at home, planning thoughtful trips, and showing up fully for the people I care about.',
    photos: ['/gallery_6.jpg', '/gallery_3.jpg'],
    interests: ['Cooking', 'Travel', 'Family time', 'Pilates', 'Film'],
    verification: {
      phoneVerified: true,
      idVerified: true,
      profileReviewed: true,
      badge: 'id',
    },
    details: {
      education: 'MBBS',
      company: 'Aster Medcity',
      annualIncome: '25–50 LPA',
      motherTongue: 'Malayalam',
      community: 'Malayali',
      familyValues: 'traditional',
      familyBackground: 'Close family with a grounded, values-first approach and a strong sense of care for one another.',
      maritalStatus: 'never-married',
      height: '5\'6"',
      diet: 'eggetarian',
      nativeVillage: 'Thrissur, Kerala',
      familyType: 'nuclear',
      mangalStatus: 'not-specified',
      employmentType: 'private-company',
      foreignStatus: 'india-based',
      smokingHabits: 'never',
      drinkingHabits: 'never',
      careerIntent: 'yes',
    },
    preferences: {
      ageRange: [28, 35],
      distance: 120,
      genderPreference: 'male',
      lookingFor: 'marriage',
      verifiedOnly: true,
      preferredMotherTongues: ['Malayalam', 'English', 'Hindi'],
      preferredCommunities: ['Malayali', 'Global'],
      preferredEducation: ['MBBS', 'Masters', 'MBA', 'PhD'],
      familyValues: ['traditional', 'balanced'],
    },
    stats: {
      profileViews: 236,
      responseRate: 91,
      profileCompletion: 97,
      boostScore: 95,
    },
    lastActiveAt: new Date(now - 1 * 60 * 60 * 1000),
    createdAt: new Date(now - 88 * 24 * 60 * 60 * 1000),
  }),
  createDefaultUser('rhea@example.com', {
    id: '5',
    name: 'Rhea Malhotra',
    age: 26,
    gender: 'female',
    location: 'New Delhi, Delhi',
    profession: 'Fashion Merchandiser',
    bio: 'Big on aesthetics, but even bigger on consistency and emotional maturity. I am looking for a partner who is clear, respectful with family, and genuinely ready for a serious chapter.',
    photos: ['/gallery_5.jpg'],
    interests: ['Fashion', 'Wellness', 'Weekend trips', 'Food trails', 'Family dinners'],
    verification: {
      phoneVerified: true,
      idVerified: false,
      profileReviewed: true,
      badge: 'phone',
    },
    details: {
      education: 'Bachelors',
      company: 'Nykaa Fashion',
      annualIncome: '15–25 LPA',
      motherTongue: 'Hindi',
      community: 'Punjabi',
      familyValues: 'balanced',
      familyBackground: 'Warm and social family that values honesty, strong communication, and togetherness.',
      maritalStatus: 'never-married',
      height: '5\'6"',
      diet: 'non-vegetarian',
      nativeVillage: 'Ludhiana, Punjab',
      familyType: 'joint',
      mangalStatus: 'non-mangal',
      employmentType: 'private-mnc',
      foreignStatus: 'india-based',
      smokingHabits: 'never',
      drinkingHabits: 'occasionally',
      careerIntent: 'optional',
    },
    preferences: {
      ageRange: [27, 33],
      distance: 70,
      genderPreference: 'male',
      lookingFor: 'marriage',
      verifiedOnly: true,
      preferredMotherTongues: ['Hindi', 'English', 'Punjabi'],
      preferredCommunities: ['Punjabi', 'North Indian', 'Global'],
      preferredEducation: ['Bachelors', 'BTech', 'Masters'],
      familyValues: ['balanced', 'progressive'],
    },
    stats: {
      profileViews: 176,
      responseRate: 70,
      profileCompletion: 89,
      boostScore: 78,
    },
    lastActiveAt: new Date(now - 34 * 60 * 1000),
    createdAt: new Date(now - 72 * 24 * 60 * 60 * 1000),
  }),
  createDefaultUser('maya@example.com', {
    id: '6',
    name: 'Maya Kapoor',
    age: 27,
    gender: 'female',
    location: 'Gurugram, Haryana',
    profession: 'Corporate Lawyer',
    bio: 'Career matters to me, but so do rituals, family dinners, and protecting space for a real personal life. I appreciate sincerity, emotional intelligence, and the kind of consistency that makes two families comfortable.',
    photos: ['/gallery_3.jpg', '/gallery_7.jpg'],
    interests: ['Reading', 'Travel', 'Family time', 'Hindustani music', 'Pilates'],
    verification: {
      phoneVerified: true,
      idVerified: true,
      profileReviewed: true,
      badge: 'id',
    },
    details: {
      education: 'Masters',
      company: 'Khaitan & Co',
      annualIncome: '25–50 LPA',
      motherTongue: 'Hindi',
      community: 'Punjabi',
      familyValues: 'traditional',
      familyBackground: 'Close Punjabi family with a modern outlook, deep loyalty, and high respect for education.',
      maritalStatus: 'never-married',
      height: '5\'4"',
      diet: 'vegetarian',
      nativeVillage: 'Patiala, Punjab',
      familyType: 'joint',
      mangalStatus: 'mangal',
      employmentType: 'private-company',
      foreignStatus: 'india-based',
      smokingHabits: 'never',
      drinkingHabits: 'occasionally',
      careerIntent: 'yes',
    },
    preferences: {
      ageRange: [28, 34],
      distance: 100,
      genderPreference: 'male',
      lookingFor: 'marriage',
      verifiedOnly: true,
      preferredMotherTongues: ['Hindi', 'Punjabi', 'English'],
      preferredCommunities: ['Punjabi', 'North Indian', 'Global'],
      preferredEducation: ['Masters', 'MBA', 'PhD'],
      familyValues: ['traditional', 'balanced'],
    },
    stats: {
      profileViews: 255,
      responseRate: 88,
      profileCompletion: 96,
      boostScore: 93,
    },
    lastActiveAt: new Date(now - 14 * 60 * 1000),
    createdAt: new Date(now - 66 * 24 * 60 * 60 * 1000),
  }),
  createDefaultUser('aditi@example.com', {
    id: '7',
    name: 'Aditi Rao',
    age: 30,
    gender: 'female',
    location: 'Hyderabad, Telangana',
    profession: 'Event Director',
    bio: 'I love beautiful spaces, decisive people, and a life that feels both playful and solid. I am looking for a generous, emotionally grounded partner who can bring warmth, maturity, and ease into the everyday.',
    photos: ['/gallery_3.jpg', '/gallery_6.jpg'],
    interests: ['Hosting', 'Travel', 'Design', 'Food trails', 'Weekend drives'],
    verification: {
      phoneVerified: true,
      idVerified: true,
      profileReviewed: false,
      badge: 'id',
    },
    details: {
      education: 'Bachelors',
      company: 'House of Gatherings',
      annualIncome: '15–25 LPA',
      motherTongue: 'Telugu',
      community: 'Telugu Reddy',
      familyValues: 'progressive',
      familyBackground: 'Close family with strong bonds, a celebratory spirit, and a lot of emotional warmth.',
      maritalStatus: 'divorced',
      height: '5\'7"',
      diet: 'non-vegetarian',
      nativeVillage: 'Vijayawada, Andhra Pradesh',
      familyType: 'nuclear',
      mangalStatus: 'not-specified',
      employmentType: 'self-employed',
      foreignStatus: 'india-based',
      smokingHabits: 'never',
      drinkingHabits: 'occasionally',
      careerIntent: 'yes',
    },
    preferences: {
      ageRange: [30, 37],
      distance: 100,
      genderPreference: 'male',
      lookingFor: 'marriage',
      verifiedOnly: true,
      preferredMotherTongues: ['Telugu', 'Hindi', 'English'],
      preferredCommunities: ['Telugu', 'Intercaste', 'Global'],
      preferredEducation: ['Bachelors', 'Masters', 'MBA'],
      familyValues: ['balanced', 'progressive'],
    },
    stats: {
      profileViews: 190,
      responseRate: 76,
      profileCompletion: 90,
      boostScore: 82,
    },
    lastActiveAt: new Date(now - 4 * 60 * 60 * 1000),
    createdAt: new Date(now - 54 * 24 * 60 * 60 * 1000),
  }),
  createDefaultUser('sneha@example.com', {
    id: '8',
    name: 'Sneha Banerjee',
    age: 31,
    gender: 'female',
    location: 'Pune, Maharashtra',
    profession: 'Startup CFO',
    bio: 'I am drawn to people who are quietly confident, thoughtful with family, and serious about building a stable future. I value trust, generosity, and the kind of humor that makes busy weeks easier.',
    photos: ['/gallery_7.jpg', '/gallery_2.jpg'],
    interests: ['Finance', 'Long drives', 'Running', 'Travel', 'Podcasts'],
    verification: {
      phoneVerified: true,
      idVerified: true,
      profileReviewed: true,
      badge: 'id',
    },
    details: {
      education: 'CA',
      company: 'Finnova Labs',
      annualIncome: '25–50 LPA',
      motherTongue: 'Bengali',
      community: 'Bengali Kayastha',
      familyValues: 'balanced',
      familyBackground: 'Professionally driven family that values generosity, discipline, and emotional maturity.',
      maritalStatus: 'never-married',
      height: '5\'8"',
      diet: 'non-vegetarian',
      nativeVillage: 'Kolkata, West Bengal',
      familyType: 'nuclear',
      mangalStatus: 'non-mangal',
      employmentType: 'private-company',
      foreignStatus: 'nri-other',
      smokingHabits: 'never',
      drinkingHabits: 'occasionally',
      careerIntent: 'yes',
    },
    preferences: {
      ageRange: [30, 38],
      distance: 80,
      genderPreference: 'male',
      lookingFor: 'marriage',
      verifiedOnly: true,
      preferredMotherTongues: ['Bengali', 'English', 'Hindi'],
      preferredCommunities: ['Bengali', 'Intercaste', 'Global'],
      preferredEducation: ['CA', 'MBA', 'Masters', 'PhD'],
      familyValues: ['balanced'],
    },
    stats: {
      profileViews: 164,
      responseRate: 74,
      profileCompletion: 92,
      boostScore: 76,
    },
    lastActiveAt: new Date(now - 23 * 60 * 60 * 1000),
    createdAt: new Date(now - 36 * 24 * 60 * 60 * 1000),
  }),
];

export const demoProfileMap = Object.fromEntries(
  [demoCurrentUser, ...demoProfiles].map((profile) => [profile.id, profile]),
) as Record<string, User>;

export const demoInterestRequests: InterestRequest[] = [
  {
    id: 'interest-1',
    fromUserId: '6',
    toUserId: '1',
    message: 'You seem thoughtful and grounded. I would be happy to connect if you feel our outlooks align.',
    status: 'pending',
    createdAt: new Date(now - 2 * 60 * 60 * 1000),
  },
  {
    id: 'interest-2',
    fromUserId: '7',
    toUserId: '1',
    message: 'Your profile feels warm and family-minded. Open to a serious conversation?',
    status: 'pending',
    createdAt: new Date(now - 20 * 60 * 60 * 1000),
  },
  {
    id: 'interest-3',
    fromUserId: '1',
    toUserId: '5',
    message: 'I liked your clarity and your pace. Happy to connect if it feels aligned for you too.',
    status: 'pending',
    createdAt: new Date(now - 8 * 60 * 60 * 1000),
  },
  {
    id: 'interest-4',
    fromUserId: '2',
    toUserId: '1',
    message: 'I think our families and outlook might align well.',
    status: 'accepted',
    createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: 'interest-5',
    fromUserId: '1',
    toUserId: '4',
    message: 'Your profile feels warm, thoughtful, and intentional. I would love to know more.',
    status: 'accepted',
    createdAt: new Date(now - 5 * 24 * 60 * 60 * 1000),
  },
];

export const demoMatches: Match[] = ['2', '4'].map((matchedUserId, index) => ({
  id: `match-${matchedUserId}`,
  userId: '1',
  matchedUserId,
  matchedUser: demoProfileMap[matchedUserId],
  status: 'matched',
  createdAt: new Date(now - (index + 1) * 2 * 24 * 60 * 60 * 1000),
}));

export const demoMessages: Record<string, Message[]> = {
  'match-2': [
    {
      id: 'msg-1',
      matchId: 'match-2',
      senderId: '2',
      content: 'Hey Arjun, I noticed we both care about family time and travel. Do you usually escape to the hills or head home on long weekends?',
      createdAt: new Date(now - 26 * 60 * 60 * 1000),
      read: true,
    },
    {
      id: 'msg-2',
      matchId: 'match-2',
      senderId: '1',
      content: 'Hi Nisha. Usually one trip to Coorg or Jaipur, one weekend with family. Your profile felt grounded in a very similar way.',
      createdAt: new Date(now - 25 * 60 * 60 * 1000),
      read: true,
    },
    {
      id: 'msg-3',
      matchId: 'match-2',
      senderId: '2',
      content: 'That sounds lovely. I am usually balancing a quick Alibaug escape with Sunday lunch at home.',
      createdAt: new Date(now - 45 * 60 * 1000),
      read: false,
    },
  ],
  'match-4': [
    {
      id: 'msg-4',
      matchId: 'match-4',
      senderId: '4',
      content: 'Hi Arjun, your profile came across as calm and sincere. How has your week been so far?',
      createdAt: new Date(now - 11 * 60 * 60 * 1000),
      read: true,
    },
  ],
};

export const demoNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: '1',
    type: 'interest',
    title: 'New interest from Maya Kapoor',
    message: 'Maya liked your profile and is open to a serious conversation.',
    href: '/profile/6',
    read: false,
    createdAt: new Date(now - 2 * 60 * 60 * 1000),
  },
  {
    id: 'notif-2',
    userId: '1',
    type: 'visitor',
    title: 'Sneha viewed your profile',
    message: 'A verified profile from Pune checked your details today.',
    href: '/profile/8',
    read: false,
    createdAt: new Date(now - 5 * 60 * 60 * 1000),
  },
  {
    id: 'notif-3',
    userId: '1',
    type: 'match',
    title: 'Interest accepted by Priya Nair',
    message: 'You can now message Priya directly.',
    href: '/chat/match-4',
    read: true,
    createdAt: new Date(now - 24 * 60 * 60 * 1000),
  },
  {
    id: 'notif-4',
    userId: '1',
    type: 'verification',
    title: 'ID verification complete',
    message: 'Your profile now shows the trusted verified badge.',
    href: '/profile',
    read: true,
    createdAt: new Date(now - 3 * 24 * 60 * 60 * 1000),
  },
];
